#!/bin/bash
# usage ./makerelease
#
# description: cat all .m files into one single m file called matlab2fortran
#
# example ./makerelease 12.12c


prog=matlab2fortran
version=`git describe`

# Preparing the doc
cp dev/README.md README
sed 's/^/\% /g' README | cat >README_TMP

# making one single mat file..
cat README_TMP dev/$prog.m dev/f*.m > $prog.m
rm README_TMP

# running tests
echo "matlab2fortran('matlab2fortran.m');quit;" | octave --traditional 
mv matlab2fortran.f90 matlab2fortran_octave.f90
echo "matlab2fortran('matlab2fortran.m');quit;"|matlab -nojvm
mv matlab2fortran.f90 matlab2fortran_matlab.f90
diff -y --suppress-common-lines --report-identical-files matlab2fortran_octave.f90 matlab2fortran_matlab.f90
mv matlab2fortran_* tests
# 
